### ISSUE TITLE
Provide more information on errors

### ISSUE THREAD

**Issue by Tuinslak** [gutworth/httpswatch#31]
Got two errors:
www.beobank.be => connect() to port 443 times out. (while https works in the browser)
and
www.belfius.be => The HTTPS site returns an error code on request. (works too; I guess it's because of the redirects?)

Would it be possible to display slightly more information about what's going on?

http://httpswatch.yeri.be/

Thanks.

**Comment by gutworth** [comment]
The first error should be fairly self-explanatory. Connecting to www.beobank.be times out after 10 seconds. In this case, it's a false positive because the server is just very slow. (It takes quite a while in the browser, too.)

The second one is actually a bug in the script in following redirects.

**Comment by Tuinslak** [comment]
Okay, odd.

From a Belgian connection:

```
$ time curl https://www.beobank.be &>/dev/null
real	0m0.325s
user	0m0.031s
sys	0m0.007s
```

From a Dutch connection:

```
# time curl https://www.beobank.be &>/dev/null
real	1m0.037s
user	0m0.004s
sys	0m0.004s
```

Ok. So redirects cause issues?

**Comment by gutworth** [comment]
Yeah, there must be some sort of networking problem.
