### ISSUE TITLE
tumblr

### ISSUE THREAD

**Issue by ChrisAntaki** [gutworth/httpswatch#45]
Currently tumblr doesn't support HTTPS for member blogs. Example: http://yahooeng.tumblr.com/ vs https://yahooeng.tumblr.com/

This means the majority of people consuming content on tumblr aren't enjoying HTTPS. Perhaps their rank should be updated to "moderate" while tumblr irons this out?

**Comment by ChrisAntaki** [comment]
What do you think, @gutworth?

**Comment by gutworth** [comment]
I guess we could use something which isn't the homepage, but is still
"official" like http://staff.tumblr.com/

**Comment by ChrisAntaki** [comment]
I think that's a good idea. The heart of tumblr is the blogs themselves. Sometimes the homepage is just an intro to a website.
