### ISSUE TITLE
Multiple redirects not considered

### ISSUE THREAD

**Issue by koop-bremen** [gutworth/httpswatch#46]
I just forked the software and made some adjustments to the config.
The banking website www.gls.de does two redirects to get the user to the https-site. However, only the first second one is not considered.

**Comment by shx82** [comment]
With the latest version I now get the following result for www.gls.de:

> A verified TLS connection can be established. (SSL Labs report)
> The HTTPS site returns an error status (503) on request. 

However, the site is perfectly reachable through https if you have a look at it in the browser.

**Comment by gutworth** [comment]
This is fixed now.
