### ISSUE TITLE
False fail on https://my.gov.au

### ISSUE THREAD

**Issue by cybershambles** [gutworth/httpswatch#54]
The fail is " The HTTPS site returns an error status (400) on request."

curl result:

[root@redletter public]# curl -I my.gov.au
HTTP/1.1 301 Moved Permanently
Date: Wed, 21 Jan 2015 09:33:32 GMT
Server: Apache
X-Frame-Options: SAMEORIGIN
Location: https://my.gov.au/
Content-Type: text/html; charset=iso-8859-1

[root@redletter public]# curl -I https://my.gov.au
HTTP/1.1 302 Found
Date: Wed, 21 Jan 2015 09:33:41 GMT
Server: HTTPD/1.0.0
X-Frame-Options: SAMEORIGIN
content-type: text/html; charset=iso-8859-1
location: https://my.gov.au/mygov
p3p: CP="NON CUR OTPi OUR NOR UNI"
Set-Cookie: PWSEAL-GOV-C=R784378955; path=/;Secure
Strict-Transport-Security: max-age=2592000

Not bad.

**Comment by gutworth** [comment]
This should be fixed now.
