### ISSUE TITLE
Change User-Agent

### ISSUE THREAD

**Issue by shx82** [gutworth/httpswatch#56]
Maybe it is a good idea to change the user agent to Mozilla, e.g.:

"Mozilla/5.0 (X11; Linux i686; rv:10.0) Gecko/20100101 Firefox/10.0"

I just had the problem that the german website www.gruene.de redirected the script to m.gruene.de, the mobile version which caused an error in the script ("Site redirects to a different domain."). Solved this by using the UA above.

I chose Mozilla since you are using it's cert store.

**Comment by gutworth** [comment]
766f9832f7e7abc1d86b6e1e3b1fb200e4a4a075
