### ISSUE TITLE
https://httpswatch.com.au/

### ISSUE THREAD

**Issue by cybershambles** [gutworth/httpswatch#65]
1) I'm growing the list tonight with 30~ businesses.
2) I've got a list of 300~ government domains I'm going to turn into a subpage.

Once this is done. Please consider listing the fork.

**Comment by gutworth** [comment]
Nice to see so much enthusiasm from the Southern Hemisphere! Have you tried coordinating with the https://httpswatchau.net/ author?

**Comment by gutworth** [comment]
We now link to https://httpswatch.com.au since pull request #66.
