### ISSUE TITLE
Include SSLLabs Report Results

### ISSUE THREAD

**Issue by DaKnOb** [gutworth/httpswatch#69]
Qualys SSL Labs has added an API a few days ago that can be queried to get all information about a host. Can this be used instead or additionally for better scoring?

https://community.qualys.com/blogs/securitylabs/2015/01/22/ssl-labs-apis-now-available-in-beta

**Comment by gutworth** [comment]
We're talking with Qualy to see if the terms of service allow HTTPSWatch to use the API.

**Comment by gutworth** [comment]
As of add13f2a45ded869135d52166c32ae3b4b0a4ada, we now have very primitive support for including the SSL Labs grade. We'll continue to improve.
