### ISSUE TITLE
Suggestion: news sites first

### ISSUE THREAD

**Issue by konklone** [gutworth/httpswatch#8]
The Linux distros are important too, but for a general audience, the news sites will resonate more strongly.

**Comment by alex** [comment]
Suggest ordering:

* Newpapers
* News
* Universities
* US Government
* Linux Distros
* Programming language

@gutworth if that sounds ok to you I can put in a PR for it.

**Comment by gutworth** [comment]
sgtm, I was just doing alphabetical without thinking.
